In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

Train test split

In [4]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

StandardScaler standardizes your features by removing the mean and scaling to unit variance:

In [6]:
#Scaling:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

#scaler.fit_transform(x_train): Learns the mean and std from the training data and scales it.

#scaler.transform(x_test): Uses the same mean and std to scale test data.

In [7]:
x_train

array([[-0.60788549, -1.07515598, -0.54829729, ..., -0.80716922,
        -0.24988069,  1.06446513],
       [ 0.45634283,  0.24358226,  0.39100039, ...,  0.59342196,
         0.8931134 ,  0.10389972],
       [-0.87394257,  0.48589459, -0.80091914, ...,  0.41849757,
         0.13165396,  0.64557195],
       ...,
       [-0.49586146, -0.7839152 , -0.5190078 , ..., -0.99061556,
        -0.64429415, -1.18778019],
       [-0.21580137,  0.53715297, -0.25824998, ..., -0.87115865,
        -0.39476727, -0.99222263],
       [ 0.40033081,  0.42298658,  0.46015613, ...,  1.48000455,
         0.19443814,  1.13113248]])

In [8]:
y_train

145    B
182    M
41     M
338    B
386    B
      ..
438    B
372    M
189    B
361    B
417    M
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
y_train

array([0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,

In [11]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [12]:
x_test_tensor.shape

torch.Size([114, 30])

### Defining the model

In [14]:
class MySimpleNN():
    
    def __init__(self,x):
        
        self.weights = torch.rand(x.shape[1], dtype = torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)
        
    def forward(self, X):
        
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor)* torch.log(1 - y_pred)).mean()
        return loss
    

In [15]:
learning_rate = 0.1
epochs = 25


## Training Pipeline

In [19]:
model = MySimpleNN(x_train_tensor)

for epoch in range(epochs):
    
    #forward pass
    y_pred = model.forward(x_train_tensor)
    
    #loss
    loss = model.loss_function(y_pred, y_train_tensor)
    
    #backward pass
    loss.backward()
    
    #parameters update
    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -= learning_rate * model.bias.grad
        
        #zero gradients
        model.weights.grad.zero_() ## note it is zero__ not just zero
        model.bias.grad.zero_()
        
        print(f'Epoch: {epoch+1}, Loss: {loss.item()}')
    

Epoch: 1, Loss: 0.5228038178045101
Epoch: 2, Loss: 0.5120305045303924
Epoch: 3, Loss: 0.501491658034025
Epoch: 4, Loss: 0.4905537203131641
Epoch: 5, Loss: 0.47908946805057995
Epoch: 6, Loss: 0.46790777810661344
Epoch: 7, Loss: 0.4570129940889921
Epoch: 8, Loss: 0.44640647135616457
Epoch: 9, Loss: 0.4360863177348086
Epoch: 10, Loss: 0.426047634161679
Epoch: 11, Loss: 0.41628317919156604
Epoch: 12, Loss: 0.406784267098947
Epoch: 13, Loss: 0.3975416808412009
Epoch: 14, Loss: 0.388546429673683
Epoch: 15, Loss: 0.37979026504205515
Epoch: 16, Loss: 0.3712659443327302
Epoch: 17, Loss: 0.36296727994339795
Epoch: 18, Loss: 0.3548890318791328
Epoch: 19, Loss: 0.3470267041175242
Epoch: 20, Loss: 0.3393762989069659
Epoch: 21, Loss: 0.33193407347636383
Epoch: 22, Loss: 0.32469633322442615
Epoch: 23, Loss: 0.3176592838425607
Epoch: 24, Loss: 0.31081895271764154
Epoch: 25, Loss: 0.30378871937797514


In [20]:
model.bias

tensor([-0.0847], dtype=torch.float64, requires_grad=True)

## Evaluation

In [22]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = ( y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.9210526347160339
